### ISSUE TITLE
Please expose `remove_gamma()` and `apply_gamma()`

### ISSUE THREAD

**Issue by apt1002** [Beinsezii/colcon#1]
Your functions `srgb_to_lrgb()` and `lrgb_to_srgb()` contain some useful formulae that implement sRGB-style gamma correction. I wish that these formulae were exposed as functions, e.g.:

```
/// Remove gamma correction from a sample.
pub fn remove_gamma(x: f32) -> f32 {
    if x <= 0.04045 {
        x / 12.92
    } else {
        ((x + 0.055) / 1.055_f32).powf(2.4)
    }
}

/// Apply gamma correction to a sample.
pub fn apply_gamma(x: f32) -> f32 {
    if x <= 0.0031308 {
        x * 12.92
    } else {
        1.055 * (x.powf(1.0 / 2.4)) - 0.055
    }
}
```

**Comment by Beinsezii** [comment]
Where would that formula even be used outside of SRGB?

**Comment by apt1002** [comment]
Grayscale images, for example.

For RGB images, it is useful when the samples are interleaved in one big array. The simple thing is to apply the formula to every element of the array.

Also for RGB images, the three colour components are sometimes in three separate arrays. Again, it's inconvenient to copy them into an array of RGB triples.

**Comment by Beinsezii** [comment]
For interleaved rgb you can use `array_chunks()` to iterate over it as an [f32; 3] and it's really fast. Never had channels as separate arrays but you can probably zip+flatten to achieve something similar.

Good idea for single-channel images though. Also maybe SRGB <-> LRGB would possibly auto-vectorize better if it was your only op.

I'll bookmark this as a TODO when I get home

**Comment by Beinsezii** [comment]
Added in colcon 0.2.1
